import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, writeFile, rm, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, toNamespacedPath } from "node:path";
import { createJiti } from "jiti";
const { isExistingPathWithinRoots, isPathWithinRoots } = await createJiti(import.meta.url).import("./path-security.ts");
test("namespaced drive roots preserve drive and directory boundaries", () => {
  const roots = new Set(["C:\\"]);
  assert.equal(isPathWithinRoots(String.raw`C:\allowed\%2e%2e\file.txt`, new Set([String.raw`C:\allowed`])), true);
  assert.equal(isPathWithinRoots(String.raw`C:\allowed%2fprivate\file.txt`, new Set([String.raw`C:\allowed`])), false);
  assert.equal(isPathWithinRoots(String.raw`\\.\pipe\fixture`, roots), false);
  assert.equal(isPathWithinRoots(String.raw`\\?\GLOBALROOT\Device\HarddiskVolume1\fixture`, roots), false);
  assert.equal(isPathWithinRoots(String.raw`\\?\C:\folder\file.txt`, roots), true);
  assert.equal(isPathWithinRoots(String.raw`\\?\D:\folder\file.txt`, roots), false);
  assert.equal(isPathWithinRoots(String.raw`C:\folder\file.txt`, new Set(["\\\\?\\C:\\"])), true);
  assert.equal(isPathWithinRoots(String.raw`\\?\C:\allowed-extra\file.txt`, new Set([String.raw`C:\allowed`])), false);
});

test("UNC namespace comparisons preserve share boundaries", () => {
  const root = String.raw`\\server\share\allowed`;
  assert.equal(isPathWithinRoots(String.raw`\\?\UNC\server\share\allowed\..\private\file.txt`, new Set([root])), false);
  assert.equal(isPathWithinRoots(String.raw`\\?\UNC\server\share\allowed\nested\..\file.txt`, new Set([root])), true);
  assert.equal(isPathWithinRoots(String.raw`\\?\UNC\server\share\allowed\.\file.txt`, new Set([root])), true);
  assert.equal(isPathWithinRoots(String.raw`\\?\UNC\server\share\allowed\file.txt`, new Set([root])), true);
  assert.equal(isPathWithinRoots(String.raw`\\SERVER\SHARE\allowed\file.txt`, new Set([String.raw`\\?\UNC\server\share\allowed`])), true);
  assert.equal(isPathWithinRoots(String.raw`\\?\UNC\server\share-extra\allowed\file.txt`, new Set([root])), false);
  assert.equal(isPathWithinRoots(String.raw`\\?\UNC\other\share\allowed\file.txt`, new Set([root])), false);
});

test("stale allowed roots do not block valid roots or authorize missing targets", async (t) => {
  const base = await mkdtemp(join(tmpdir(), "pi-path-roots-"));
  t.after(() => rm(base, { recursive: true, force: true }));
  const allowed = join(base, "allowed");
  await mkdir(allowed);
  const file = join(allowed, "fixture.txt");
  await writeFile(file, "fixture");
  assert.equal(isPathWithinRoots(file, new Set()), false);
  assert.equal(isExistingPathWithinRoots(file, new Set()), false);
  assert.equal(isExistingPathWithinRoots(toNamespacedPath(file), new Set()), false);
  const literalEncodedDir = join(allowed, "%2e%2e");
  await mkdir(literalEncodedDir);
  const literalEncodedFile = join(literalEncodedDir, "%2f.txt");
  await writeFile(literalEncodedFile, "literal filename");
  assert.equal(isExistingPathWithinRoots(literalEncodedFile, new Set([allowed])), true);
  assert.equal(isExistingPathWithinRoots(file, new Set([literalEncodedDir])), false);
  if (process.platform === "win32") {
    assert.equal(isPathWithinRoots(toNamespacedPath(file), new Set([allowed])), true);
    assert.equal(isPathWithinRoots(file, new Set([toNamespacedPath(allowed)])), true);
    assert.equal(isPathWithinRoots(toNamespacedPath(base), new Set([allowed])), false);
    assert.equal(isExistingPathWithinRoots(toNamespacedPath(file), new Set([allowed])), true);
    assert.equal(isExistingPathWithinRoots(file, new Set([toNamespacedPath(allowed)])), true);
    assert.equal(isExistingPathWithinRoots(toNamespacedPath(base), new Set([allowed])), false);
    assert.equal(isExistingPathWithinRoots(file.toUpperCase(), new Set([allowed])), true);
    assert.equal(isExistingPathWithinRoots(file.replaceAll("\\", "/"), new Set([allowed.toUpperCase()])), true);
  }
  const specialRoot = join(allowed, "中文 # 100%");
  await mkdir(specialRoot);
  const specialFile = join(specialRoot, "文件 #%.txt");
  await writeFile(specialFile, "special");
  assert.equal(isExistingPathWithinRoots(specialFile, new Set([specialRoot])), true);
  assert.equal(isExistingPathWithinRoots(specialFile, new Set([allowed])), true);
  assert.equal(isExistingPathWithinRoots(file, new Set([specialRoot])), false);
  assert.equal(isExistingPathWithinRoots(`${file}\0ignored`, new Set([allowed])), false);
  assert.equal(isExistingPathWithinRoots(file, new Set([`${allowed}\0ignored`])), false);
  assert.equal(isExistingPathWithinRoots(file, new Set([`${allowed}\0ignored`, allowed])), true);
  const sibling = join(base, "allowed-extra");
  await mkdir(sibling);
  await writeFile(join(sibling, "fixture.txt"), "not allowed");
  assert.equal(isExistingPathWithinRoots(join(sibling, "fixture.txt"), new Set([allowed])), false);
  assert.equal(isExistingPathWithinRoots(`${allowed}/../allowed-extra/fixture.txt`, new Set([allowed])), false);
  const missing = join(base, "removed");
  assert.equal(isExistingPathWithinRoots(file, new Set([missing, allowed])), true);
  assert.equal(isExistingPathWithinRoots(file, new Set([missing])), false);
  assert.equal(isExistingPathWithinRoots(join(allowed, "absent.txt"), new Set([allowed])), false);
  assert.equal(isExistingPathWithinRoots(base, new Set([allowed])), false);
  const outside = join(base, "outside");
  await mkdir(outside);
  await writeFile(join(outside, "secret.txt"), "outside");
  const inside = join(allowed, "inside");
  await mkdir(inside);
  await writeFile(join(inside, "public.txt"), "inside");
  const linkType = process.platform === "win32" ? "junction" : "dir";
  await symlink(outside, join(allowed, "escape"), linkType);
  await symlink(inside, join(allowed, "alias"), linkType);
  assert.equal(isExistingPathWithinRoots(join(allowed, "escape", "secret.txt"), new Set([allowed])), false);
  if (process.platform === "win32") {
    assert.equal(isExistingPathWithinRoots(toNamespacedPath(join(allowed, "escape", "secret.txt")), new Set([allowed])), false);
    assert.equal(isExistingPathWithinRoots(join(allowed, "escape", "secret.txt"), new Set([toNamespacedPath(allowed)])), false);
  }
  assert.equal(isExistingPathWithinRoots(join(allowed, "alias", "public.txt"), new Set([allowed])), true);
  await writeFile(join(outside, "public.txt"), "outside replacement");
  await rm(join(allowed, "alias"));
  await symlink(outside, join(allowed, "alias"), linkType);
  assert.equal(isExistingPathWithinRoots(join(allowed, "alias", "public.txt"), new Set([allowed])), false);
  const rootAlias = join(base, "root-alias");
  await symlink(allowed, rootAlias, linkType);
  assert.equal(isExistingPathWithinRoots(join(rootAlias, "fixture.txt"), new Set([rootAlias])), true);
  assert.equal(isExistingPathWithinRoots(file, new Set([rootAlias])), true);
  assert.equal(isExistingPathWithinRoots(join(outside, "secret.txt"), new Set([rootAlias])), false);
  assert.equal(isExistingPathWithinRoots(join(rootAlias, "escape", "secret.txt"), new Set([rootAlias])), false);
  await rm(outside, { recursive: true });
  const dangling = join(allowed, "escape");
  assert.equal(isExistingPathWithinRoots(join(dangling, "secret.txt"), new Set([allowed])), false);
  assert.equal(isExistingPathWithinRoots(file, new Set([dangling])), false);
  assert.equal(isExistingPathWithinRoots(file, new Set([dangling, allowed])), true);
});
